### ISSUE TITLE
Media Library Thumbnail Size not working

### ISSUE THREAD

**Issue by dannystarkDE** [mindkomm/timmy#41]
Hello!

I have a question about the image size in the Media Library.
Is it possible that the plugin also affects the thumbnail size in the backend? Currently, images are no longer reduced and always included in full size.

What could be the reason for this?

![screenshot_ 2021-06-15_11-55-39](https://user-images.githubusercontent.com/8641492/122033309-b0eac680-cdd0-11eb-8dd7-61bcec5aba90.png)

My config: 

```
add_filter("timmy/sizes", function ($sizes) {
    return array(
        "thumbnail" => array(
            "resize" => array(150, 150),
            "srcset" => array(
                25,
                15,
                10,
            ),
            "name" => "Thumbnail",
            "post_types" => array("all"),
        ),
        "medium" => array(
            "resize" => array(240, 240),
            "name" => "Medium",
            "post_types" => array("all"),
        ),
        "medium_large" => array(
            "resize" => array(768),
            "name" => "Medium Large",
            "post_types" => array("all"),
        ),
        "large" => array(
            "resize" => array(1920, 1080),
            "name" => "Large",
            "post_types" => array("all"),
        ),
        "landscape" => array(
            "resize" => array(32, 20, "center"),
            "name" => "Landscape",
            "srcset" => array(
                80,
                60,
                45,
                35,
                25,
                15,
                10,
            ),
            "post_types" => array("all"),
        ),
        "panorama" => array(
            "resize" => array(32, 12),
            "name" => "Panorama",
            "srcset" => array(
                80,
                60,
                45,
                35,
                25,
                15,
                10,
            ),
            "post_types" => array("all"),
        ),
        "portrait" => array(
            "resize" => array(28, 36, "bottom"),
            "name" => "Portrait",
            "srcset" => array(
                80,
                60,
                45,
                35,
                25,
                15,
                10,
            ),
            "post_types" => array("all"),
        ),
        "custom" => array(
            "resize" => array(24, 30, "bottom"),
            "name" => "Portrait",
            "srcset" => array(
                80,
                60,
                45,
                35,
                25,
                15,
                10,
            ),
            "post_types" => array("all"),
        ),
        "square" => array(
            "resize" => array(20, 20, "center"),
            "srcset" => array(
                80,
                60,
                45,
                35,
                25,
                15,
                10,
            ),
            "name" => "Square",
            "post_types" => array("all"),
        ),
        "auto" => array(
            "resize" => array(30),
            "srcset" => array(
                array(2560),
                array(1920),
                array(1400),
                array(1100),
                array(800),
                array(500),
                array(300),
            ),
            "name" => "Auto",
            "post_types" => array("all"),
        ),
    );
});

```

**Comment by gchtr** [comment]
> Is it possible that the plugin also affects the thumbnail size in the backend? Currently, images are no longer reduced and always included in full size.

Yes, it actually does affect the sizes in the backend. Because Timmy hooks into how images are generated in WordPress core, this also affects the admin. When thumbnails are loaded in the backend, Timmy should load the [thumbnail size](https://github.com/mindkomm/timmy/blob/master/docs/image-configuration.md#the-thumbnail-key).

I just checked with the newest version of WordPress and your filter settings. For me, all works as expected.

The HTML that I see in your small developer tools preview looks like you’re looking at the markup for the big preview for an image. Could that be the case?

![](https://user-images.githubusercontent.com/2084481/127380184-99dcac3e-3507-486b-891b-ab24ba71b6ed.png)

Compare to this. Here, it’s supposed to load the full size of the image.

![](https://user-images.githubusercontent.com/2084481/127380587-4c36a672-14b0-4e74-b7da-5d34b87334fd.png)

In cases like these, it’s also helpful to look at the Network tab in your browser console and filter it by graphics to see what actually gets loaded by the browser:

![](https://user-images.githubusercontent.com/2084481/127381013-d14efe3f-6ef4-4a7a-b2bf-f975af09f0c1.png)

If the full image size is loaded in your case, I’ll have to look into that more closely.

**Comment by dannystarkDE** [comment]
Hey. Thank you for answer. I found my mistake.

It looks like the Timmy Config was too deep down in the functions.php. (At the end of the "function theme_supports()")
Now i include the Timmy config in the Timber Constructor and everything worked as expected. 

![screenshot_ 2021-09-23_21-53-53](https://user-images.githubusercontent.com/8641492/134575168-dbba7410-9be9-4975-abec-ec36c55966ac.png)
![screenshot_ 2021-09-23_21-52-30](https://user-images.githubusercontent.com/8641492/134575175-b8645baa-af47-4b54-a85a-4a537e2e916b.png)

**Comment by gchtr** [comment]
Hey @dannystarkDE

Thanks for posting how you solved this issue. I think it’s good to configure Timmy as early as possible, which means not putting it into a special hook.
